version: "3.9"  # optional since v1.27.0
services:
  jitsi-puppet-video:
    image: jameswickenden/jitsi-puppet-video:6.0
    environment:
      - URL=https://192.168.0.102/lan
      - TIMEOUT=60
      - FILE=lipsum
      - HELP=true
