version: "3.9"  # optional since v1.27.0
services:
  jitsi-puppet-video:
    image: jameswickenden/jitsi-puppet-video:6.0
    environment:
      - URL2=https://192.168.0.102/lan
      - URL=https://meet.jit.si/jameswick
      - TIMEOUT=3600
      - FILE=lipsum
